FROM mcr.microsoft.com/devcontainers/python:3.11

# Instala matplotlib y yfinance como dependencias comunes (redundante con postCreateCommand, pero útil para depuración)
RUN pip install --upgrade pip
